
server:
  port: 80

spring:
  application:
    name: demoknife4jopenapi2springbootstarter


# 配置日志地址
logging:
  config: classpath:logback-spring.xml


# Knife4j????
#knife4j:
#  enable: true
#  basic:
#    enable: false
#    username: admin
#    password: 123456
#  openapi:
#    title: API文档
#    description: "API文档"
#    concat: webVueBlog
#    email: 1024bibi.com
#    url: http://gitee.com/webVueBlog
#    version: v1.0.0
#    license: MIT
#    group:
#      demo:
#        group-name: demoknife4jopenapi2springbootstarter
#        api-rule: package
#        api-rule-resources:
#          - com.example.webvueblog.demoknife4jopenapi2springbootstarter
